name: Data Schema Code Convention

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  schema_linter:
    name: JSON and SQL Schema Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # --- JSON перевірка ---
      - name: Install JSONLint
        run: npm install -g @prantlf/jsonlint

      - name: Validate JSON Schema
        run: |
          echo "Running JSON Linter..."
          jsonlint $GITHUB_WORKSPACE/DataSchema.json

      # --- SQL перевірка ---
      - name: Install SQLFluff
        run: pip install sqlfluff

      - name: Validate SQL Schema
        run: |
          echo "Running SQLFluff..."
          sqlfluff lint $GITHUB_WORKSPACE/DataSchema.sql --dialect postgres
