name: Print Software Versions

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  data_processing_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Show software versions (Application Server)
        run: |
          echo "Версії ПЗ для обробки даних:"
          python3 --version
          node --version
          java -version

  database_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Show DBMS versions (Database Server)
        run: |
          echo "Версії баз даних:"
          psql --version || echo "PostgreSQL not installed"
          mongo --version || echo "MongoDB not installed"
