name: Program Code Convention Check

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    name: Lint Python Code (flake8)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8 on repository files (expect fail if code has errors)
        run: |
          echo "=== Checking ProgramCode.py ==="
          flake8 ProgramCode.py
          echo "=== Checking ProgramCodeModified.py ==="
          flake8 ProgramCodeModified.py
